# default configuration
baseURL = "http://examplesite.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = ""

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "More Info"
weight = 1

# [[menu.main]]
# URL = "purchase"
# name = "Purchase"
# weight = 2

# [[menu.main]]
# URL = "area_info"
# name = "Area Info"
# weight = 3

# [[menu.main]]
# URL = "portfolio"
# name = "Portfolio"
# weight = 4

# [[menu.main]]
# URL = "contact"
# name = "Contact"
# weight = 5


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#d2ba9a"
# contact info
phone = "(604) 469-1651"
email = "rlphoto [at] shaw.ca"
address = "Port Moody, BC, Canada"
# meta description
author = "Steve Chapman"
description = "Pink Mountain's Rare and Endangered Species"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID
# copyright
copyright = "Website Copyright &copy; 2022 Canadian Map Makers"

# - theme by [Gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formspree.io/f/xqkwnpbb" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
URL = "https://www.facebook.com/CanadianMapMakers/"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/overdue_app/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/CAN_MapMakers"
